/* Generated by cbindgen - DO NOT EDIT */
/* Scatter plot rendering library - C API */


#ifndef PLOTFFI_H
#define PLOTFFI_H

#pragma once

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Options for configuring the scatter plot.
 */
typedef struct PlotOptions {
  /**
   * Width of the output image in pixels
   */
  uint32_t width;
  /**
   * Height of the output image in pixels
   */
  uint32_t height;
  /**
   * Radius of scatter plot markers in pixels
   */
  uint32_t marker_radius;
  /**
   * If nonzero, automatically compute axis ranges from data (with 2% padding)
   */
  uint8_t auto_range;
  /**
   * Minimum X axis value (used when auto_range == 0)
   */
  double x_min;
  /**
   * Maximum X axis value (used when auto_range == 0)
   */
  double x_max;
  /**
   * Minimum Y axis value (used when auto_range == 0)
   */
  double y_min;
  /**
   * Maximum Y axis value (used when auto_range == 0)
   */
  double y_max;
} PlotOptions;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Renders a scatter plot to a PNG file.
 *
 * # Parameters
 * - `path`: NUL-terminated UTF-8 path to the output PNG file
 * - `xs`: Pointer to array of X coordinates
 * - `ys`: Pointer to array of Y coordinates
 * - `n`: Number of points (length of xs and ys arrays)
 * - `opt`: Plot configuration options
 *
 * # Returns
 * - 0 on success
 * - 1 on failure (call `plot_last_error_message()` for details)
 *
 * # Safety
 * - `path` must be a valid NUL-terminated UTF-8 string
 * - `xs` and `ys` must point to arrays of at least `n` elements
 * - `n` must be greater than 0
 */
int32_t plot_scatter_png(const char *path,
                         const double *xs,
                         const double *ys,
                         uintptr_t n,
                         struct PlotOptions opt);

/**
 * Returns the last error message, or NULL if no error has occurred.
 *
 * The returned pointer is valid until the next call to `plot_scatter_png()`.
 * The string is NUL-terminated UTF-8.
 *
 * # Safety
 * The returned pointer must not be freed by the caller.
 */
const char *plot_last_error_message(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLOTFFI_H */
